# Generated by Django 4.1.3 on 2022-12-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_site", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="slug",
            field=models.SlugField(
                default=1, max_length=64, unique=True, verbose_name="URL"
            ),
            preserve_default=False,
        ),
    ]
