# Generated by Django 4.1.3 on 2023-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_site", "0002_note_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorize",
            name="description",
            field=models.TextField(
                default="Приглашаем вас авторизоваться для просмотра заметок",
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="description",
            field=models.TextField(
                default="Заполните поля ниже", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tag",
            field=models.CharField(default=1, max_length=64, verbose_name="Тег"),
            preserve_default=False,
        ),
    ]
