# Generated by Django 4.1.3 on 2022-12-26 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notes_site", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailhash",
            name="hash_text",
            field=models.CharField(
                default=uuid.uuid4, max_length=64, verbose_name="Хэш"
            ),
        ),
        migrations.AlterField(
            model_name="emailhash",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
    ]
