# Generated by Django 4.1.3 on 2022-12-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes_site", "0003_note_user_alter_emailhash_hash_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorize",
            options={
                "verbose_name": "Авторизация",
                "verbose_name_plural": "Авторизации",
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "verbose_name": "Ркгистрация",
                "verbose_name_plural": "Регистрации",
            },
        ),
        migrations.AlterModelTable(
            name="authorize",
            table="Authorize",
        ),
        migrations.AlterModelTable(
            name="registration",
            table="Registration",
        ),
    ]
