# Generated by Django 4.1.3 on 2023-01-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_site", "0003_alter_authorize_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailsettings",
            name="description",
            field=models.TextField(
                default="Активация аккаунта", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="mailsettings",
            name="domen",
            field=models.CharField(
                default="127.0.0.0.1:8000", max_length=64, verbose_name="Домен"
            ),
        ),
        migrations.AlterField(
            model_name="mailsettings",
            name="title",
            field=models.CharField(
                default="Актвация аккаунта", max_length=128, verbose_name="Заголовок"
            ),
        ),
    ]
