# Generated by Django 4.1.3 on 2023-01-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes_site", "0004_alter_mailsettings_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tags",
            old_name="note",
            new_name="tags",
        ),
    ]
