# Generated by Django 4.1.3 on 2022-12-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes_site", "0005_user_username_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domen", models.CharField(max_length=64, verbose_name="Домен")),
                ("title", models.CharField(max_length=128, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Настройки почты",
                "verbose_name_plural": "Настройки почт",
                "db_table": "mail_setinngs",
            },
        ),
        migrations.AlterModelOptions(
            name="registration",
            options={
                "verbose_name": "Регистрация",
                "verbose_name_plural": "Регистрации",
            },
        ),
    ]
